# Generated by Django 3.0.3 on 2020-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleave', '0002_auto_20201026_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
