# Generated by Django 3.0.3 on 2020-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleave', '0003_auto_20201026_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leavetype',
            field=models.CharField(max_length=50),
        ),
    ]
