# Generated by Django 3.0.3 on 2020-10-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeleave', '0004_auto_20201027_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='leavetype',
            field=models.CharField(max_length=100),
        ),
    ]
